// 올웨이즈 타겟 페르소나 기반 mock 유저 100명
// 35-52세 여성, 건강기능식품/바디케어 관심 유저군

const MOCK_USERS = [
  // ── Cluster A: 40대 주부, 비타민/면역력 집중 (30명) ──────────────────
  { id: 'u001', age: 43, occupation: '주부', region: '경기', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },
  { id: 'u002', age: 46, occupation: '주부', region: '서울', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '피로회복'] },
  { id: 'u003', age: 41, occupation: '주부', region: '인천', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '피부'] },
  { id: 'u004', age: 48, occupation: '주부', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '혈관건강'] },
  { id: 'u005', age: 44, occupation: '주부', region: '부산', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },
  { id: 'u006', age: 42, occupation: '주부', region: '대구', categories: ['비타민/영양제', '바디케어'], concerns: ['면역력', '피부'] },
  { id: 'u007', age: 47, occupation: '주부', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '뼈/관절'] },
  { id: 'u008', age: 45, occupation: '주부', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '피로회복'] },
  { id: 'u009', age: 40, occupation: '주부', region: '광주', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },
  { id: 'u010', age: 49, occupation: '주부', region: '서울', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '혈당관리'] },
  { id: 'u011', age: 43, occupation: '주부', region: '경기', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '피부'] },
  { id: 'u012', age: 46, occupation: '주부', region: '대전', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '피로회복'] },
  { id: 'u013', age: 41, occupation: '주부', region: '서울', categories: ['비타민/영양제', '바디케어'], concerns: ['면역력', '피부'] },
  { id: 'u014', age: 44, occupation: '주부', region: '경기', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },
  { id: 'u015', age: 50, occupation: '주부', region: '부산', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '혈관건강'] },
  { id: 'u016', age: 38, occupation: '주부', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '피부'] },
  { id: 'u017', age: 47, occupation: '주부', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '눈건강'] },
  { id: 'u018', age: 42, occupation: '주부', region: '인천', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },
  { id: 'u019', age: 45, occupation: '주부', region: '서울', categories: ['비타민/영양제', '바디케어'], concerns: ['면역력', '피부'] },
  { id: 'u020', age: 48, occupation: '주부', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '뼈/관절'] },
  { id: 'u021', age: 39, occupation: '주부', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },
  { id: 'u022', age: 43, occupation: '주부', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '피로회복'] },
  { id: 'u023', age: 46, occupation: '주부', region: '대구', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '피부'] },
  { id: 'u024', age: 44, occupation: '주부', region: '서울', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '혈관건강'] },
  { id: 'u025', age: 41, occupation: '주부', region: '경기', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },
  { id: 'u026', age: 52, occupation: '주부', region: '부산', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '혈당관리'] },
  { id: 'u027', age: 40, occupation: '주부', region: '서울', categories: ['비타민/영양제', '바디케어'], concerns: ['면역력', '피부'] },
  { id: 'u028', age: 47, occupation: '주부', region: '경기', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '뼈/관절'] },
  { id: 'u029', age: 45, occupation: '주부', region: '인천', categories: ['비타민/영양제', '건강식품'], concerns: ['면역력', '피로회복'] },
  { id: 'u030', age: 43, occupation: '주부', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['면역력', '장건강'] },

  // ── Cluster B: 35-42 직장인 여성, 피로회복/피부 집중 (25명) ─────────
  { id: 'u031', age: 37, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '면역력'] },
  { id: 'u032', age: 35, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '피부'] },
  { id: 'u033', age: 39, occupation: '직장인', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '면역력'] },
  { id: 'u034', age: 36, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '바디케어'], concerns: ['피로회복', '피부'] },
  { id: 'u035', age: 41, occupation: '직장인', region: '부산', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '장건강'] },
  { id: 'u036', age: 38, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '눈건강'] },
  { id: 'u037', age: 35, occupation: '직장인', region: '경기', categories: ['비타민/영양제', '바디케어'], concerns: ['피로회복', '피부'] },
  { id: 'u038', age: 40, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '면역력'] },
  { id: 'u039', age: 36, occupation: '교사', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '면역력'] },
  { id: 'u040', age: 42, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '피부'] },
  { id: 'u041', age: 37, occupation: '직장인', region: '인천', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '면역력'] },
  { id: 'u042', age: 39, occupation: '교사', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '장건강'] },
  { id: 'u043', age: 35, occupation: '직장인', region: '경기', categories: ['비타민/영양제', '바디케어'], concerns: ['피로회복', '피부'] },
  { id: 'u044', age: 41, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '눈건강'] },
  { id: 'u045', age: 38, occupation: '간호사', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '면역력'] },
  { id: 'u046', age: 36, occupation: '직장인', region: '부산', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '피부'] },
  { id: 'u047', age: 40, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '장건강'] },
  { id: 'u048', age: 37, occupation: '교사', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '면역력'] },
  { id: 'u049', age: 42, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '바디케어'], concerns: ['피로회복', '피부'] },
  { id: 'u050', age: 35, occupation: '직장인', region: '대구', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '면역력'] },
  { id: 'u051', age: 39, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '피부'] },
  { id: 'u052', age: 36, occupation: '간호사', region: '경기', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '면역력'] },
  { id: 'u053', age: 41, occupation: '직장인', region: '서울', categories: ['비타민/영양제', '유산균/콜라겐'], concerns: ['피로회복', '장건강'] },
  { id: 'u054', age: 38, occupation: '직장인', region: '인천', categories: ['비타민/영양제', '건강식품'], concerns: ['피로회복', '눈건강'] },
  { id: 'u055', age: 40, occupation: '교사', region: '서울', categories: ['비타민/영양제', '바디케어'], concerns: ['피로회복', '피부'] },

  // ── Cluster C: 45-52 주부, 피부/유산균/콜라겐 집중 (25명) ───────────
  { id: 'u056', age: 48, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '장건강'] },
  { id: 'u057', age: 50, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '면역력'] },
  { id: 'u058', age: 46, occupation: '주부', region: '부산', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '장건강'] },
  { id: 'u059', age: 52, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '뼈/관절'] },
  { id: 'u060', age: 47, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '면역력'] },
  { id: 'u061', age: 49, occupation: '주부', region: '대구', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '장건강'] },
  { id: 'u062', age: 45, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '면역력'] },
  { id: 'u063', age: 51, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '건강식품'], concerns: ['피부', '혈관건강'] },
  { id: 'u064', age: 48, occupation: '주부', region: '인천', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '장건강'] },
  { id: 'u065', age: 46, occupation: '자영업자', region: '서울', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '피로회복'] },
  { id: 'u066', age: 50, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '면역력'] },
  { id: 'u067', age: 47, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '장건강'] },
  { id: 'u068', age: 52, occupation: '주부', region: '부산', categories: ['유산균/콜라겐', '건강식품'], concerns: ['피부', '혈당관리'] },
  { id: 'u069', age: 45, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '면역력'] },
  { id: 'u070', age: 49, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '장건강'] },
  { id: 'u071', age: 46, occupation: '주부', region: '대전', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '뼈/관절'] },
  { id: 'u072', age: 48, occupation: '자영업자', region: '서울', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '피로회복'] },
  { id: 'u073', age: 51, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '건강식품'], concerns: ['피부', '혈관건강'] },
  { id: 'u074', age: 45, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '면역력'] },
  { id: 'u075', age: 50, occupation: '주부', region: '인천', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '장건강'] },
  { id: 'u076', age: 47, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '면역력'] },
  { id: 'u077', age: 52, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '건강식품'], concerns: ['피부', '혈당관리'] },
  { id: 'u078', age: 46, occupation: '주부', region: '경기', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '장건강'] },
  { id: 'u079', age: 49, occupation: '주부', region: '부산', categories: ['유산균/콜라겐', '비타민/영양제'], concerns: ['피부', '면역력'] },
  { id: 'u080', age: 48, occupation: '주부', region: '서울', categories: ['유산균/콜라겐', '바디케어'], concerns: ['피부', '장건강'] },

  // ── Cluster D: 38-50 혼합, 혈당/혈관/다이어트 관심 (20명) ───────────
  { id: 'u081', age: 48, occupation: '주부', region: '서울', categories: ['건강식품', '비타민/영양제'], concerns: ['혈당관리', '혈관건강'] },
  { id: 'u082', age: 45, occupation: '직장인', region: '경기', categories: ['건강식품', '간식'], concerns: ['다이어트', '혈당관리'] },
  { id: 'u083', age: 50, occupation: '주부', region: '서울', categories: ['건강식품', '비타민/영양제'], concerns: ['혈관건강', '뼈/관절'] },
  { id: 'u084', age: 42, occupation: '자영업자', region: '부산', categories: ['건강식품', '유산균/콜라겐'], concerns: ['다이어트', '장건강'] },
  { id: 'u085', age: 47, occupation: '주부', region: '경기', categories: ['건강식품', '비타민/영양제'], concerns: ['혈당관리', '면역력'] },
  { id: 'u086', age: 39, occupation: '직장인', region: '서울', categories: ['건강식품', '간식'], concerns: ['다이어트', '피로회복'] },
  { id: 'u087', age: 52, occupation: '주부', region: '경기', categories: ['건강식품', '비타민/영양제'], concerns: ['혈관건강', '혈당관리'] },
  { id: 'u088', age: 44, occupation: '주부', region: '대구', categories: ['건강식품', '유산균/콜라겐'], concerns: ['다이어트', '장건강'] },
  { id: 'u089', age: 49, occupation: '주부', region: '서울', categories: ['건강식품', '비타민/영양제'], concerns: ['혈당관리', '뼈/관절'] },
  { id: 'u090', age: 38, occupation: '직장인', region: '경기', categories: ['건강식품', '간식'], concerns: ['다이어트', '피로회복'] },
  { id: 'u091', age: 46, occupation: '주부', region: '인천', categories: ['건강식품', '비타민/영양제'], concerns: ['혈관건강', '면역력'] },
  { id: 'u092', age: 43, occupation: '자영업자', region: '서울', categories: ['건강식품', '유산균/콜라겐'], concerns: ['다이어트', '장건강'] },
  { id: 'u093', age: 51, occupation: '주부', region: '경기', categories: ['건강식품', '비타민/영양제'], concerns: ['혈당관리', '혈관건강'] },
  { id: 'u094', age: 40, occupation: '교사', region: '서울', categories: ['건강식품', '간식'], concerns: ['다이어트', '면역력'] },
  { id: 'u095', age: 48, occupation: '주부', region: '부산', categories: ['건강식품', '비타민/영양제'], concerns: ['혈관건강', '뼈/관절'] },
  { id: 'u096', age: 37, occupation: '직장인', region: '서울', categories: ['건강식품', '유산균/콜라겐'], concerns: ['다이어트', '피로회복'] },
  { id: 'u097', age: 50, occupation: '주부', region: '경기', categories: ['건강식품', '비타민/영양제'], concerns: ['혈당관리', '혈관건강'] },
  { id: 'u098', age: 45, occupation: '주부', region: '서울', categories: ['건강식품', '바디케어'], concerns: ['다이어트', '피부'] },
  { id: 'u099', age: 42, occupation: '직장인', region: '경기', categories: ['건강식품', '비타민/영양제'], concerns: ['혈관건강', '피로회복'] },
  { id: 'u100', age: 47, occupation: '주부', region: '서울', categories: ['건강식품', '유산균/콜라겐'], concerns: ['혈당관리', '장건강'] },
];

module.exports = { MOCK_USERS };
